a = 2
b= True
c= 2.902
d = 3+2j
str1 = "anandu"
list1 = [1,"one","two",2]
tuple1 = (1,"one",2)
dict1 = {1:"one",2:"two"}
set1 = {1,"anandu","gokul",48}
print(f"type of a = {type(a)}")
print(f"type of b = {type(b)}")
print(f"type of c = {type(c)}")
print(f"type of d = {type(d)}")
print(f"type of str1 = {type(str1)}")
print(f"type of set1 = {type(set1)}")
print(f"type of list1 = {type(list1)}")
print(f"type of tuple1 = {type(tuple1)}")
print(f"type of dict1 = {type(dict1)}")
